# Generated by Django 5.0.1 on 2024-01-22 13:25

import blog.models.post
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='project_picture',
            field=models.ImageField(blank=True, upload_to=blog.models.post.blog_image_path),
        ),
    ]
