# Generated by Django 5.0.1 on 2024-01-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_mainuser_bio_remove_mainuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='project_picture',
            new_name='image',
        ),
    ]
