# Generated by Django 5.0.1 on 2024-01-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_project_picture_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
