# Generated by Django 5.0.1 on 2024-01-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_mainuser_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='veriifed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
