# Generated by Django 5.0.1 on 2024-01-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_mainuser_veriifed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainuser',
            old_name='veriifed',
            new_name='verifed',
        ),
    ]
