# Generated by Django 5.0.1 on 2024-01-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_verifed_mainuser_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author',
            new_name='user_id',
        ),
    ]
